# Generated by Django 5.2 on 2025-07-09 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Premium', 'Premium')], default='Free', help_text='The current subscription plan (Free, Basic, Premium).', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True, help_text='The date when the subscription started.')),
                ('end_date', models.DateField(blank=True, help_text='The date when the subscription is set to end (optional).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the subscription is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the subscription record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the subscription record was last updated.')),
                ('user', models.OneToOneField(help_text='The user associated with this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
